using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared._ST14.ST14Resources;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._ST14.ST14Resources.UI;

[GenerateTypedNameReferences]
public sealed partial class ST14ResourceExtractorWindow : FancyWindow
{
    [Dependency] private IPrototypeManager _prototype = default!;

    private readonly StyleBoxFlat _activeSlotStyle = new()
    {
        BorderColor = Color.FromHex("#D4891C"),
        BorderThickness = new Thickness(2),
    };

    private readonly StyleBoxFlat _inactiveSlotStyle = new()
    {
        BorderColor = Color.FromHex("#4F4F4F"),
        BorderThickness = new Thickness(1),
    };

    public event Action? OnToggle;
    public event Action<int>? OnSelectSlot;
    public event Action<int>? OnSlotButton;
    public event Action<bool>? OnAutoSwitchChanged;

    public ST14ResourceExtractorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Slot1Panel.PanelOverride = _inactiveSlotStyle;
        Slot2Panel.PanelOverride = _inactiveSlotStyle;

        ToggleButton.OnPressed += _ => OnToggle?.Invoke();
        FeedSlot1Button.OnPressed += _ => OnSelectSlot?.Invoke(0);
        FeedSlot2Button.OnPressed += _ => OnSelectSlot?.Invoke(1);
        Slot1Button.OnPressed += _ => OnSlotButton?.Invoke(0);
        Slot2Button.OnPressed += _ => OnSlotButton?.Invoke(1);
        AutoSwitchCheckBox.OnToggled += args => OnAutoSwitchChanged?.Invoke(args.Pressed);
    }

    public void UpdateState(ST14ResourceExtractorBoundUserInterfaceState state)
    {
        var color = _prototype.Index(state.Resource).Color;

        UpdateSlot(state, 0, color, Slot1Panel, Slot1Gauge, Slot1Label, Slot1Button);
        UpdateSlot(state, 1, color, Slot2Panel, Slot2Gauge, Slot2Label, Slot2Button);

        StatusLabel.SetMarkup(Loc.GetString(state.Status switch
        {
            ST14ResourceExtractorStatus.Working => "st14-extractor-ui-status-working",
            ST14ResourceExtractorStatus.NoSpace => "st14-extractor-ui-status-no-space",
            _ => "st14-extractor-ui-status-off",
        }));

        RateLabel.Text = state.Status == ST14ResourceExtractorStatus.Working
            ? Loc.GetString("st14-extractor-ui-rate", ("rate", state.Rate.ToString("0.#")))
            : Loc.GetString("st14-extractor-ui-rate-none");

        AutoSwitchCheckBox.Pressed = state.AutoSwitch;

        ToggleButton.Text = Loc.GetString(state.Status == ST14ResourceExtractorStatus.Working
            ? "st14-extractor-ui-turn-off"
            : "st14-extractor-ui-turn-on");
    }

    private void UpdateSlot(
        ST14ResourceExtractorBoundUserInterfaceState state,
        int index,
        Color color,
        PanelContainer panel,
        ST14ResourceGauge gauge,
        Label label,
        Button button)
    {
        var slot = state.Slots[index];
        var other = state.Slots[(index + 1) % state.Slots.Length];

        panel.PanelOverride = index == state.ActiveSlot ? _activeSlotStyle : _inactiveSlotStyle;

        var scale = slot.HasCapsule ? slot.Capacity : other.Capacity;
        gauge.FillColor = color;
        gauge.SetValues(slot.Amount.Float(), scale.Float());

        label.Text = slot.HasCapsule
            ? Loc.GetString("st14-extractor-ui-slot-amount", ("amount", slot.Amount.Int()), ("capacity", slot.Capacity.Int()))
            : Loc.GetString("st14-extractor-ui-slot-empty");

        button.Text = Loc.GetString(slot.HasCapsule ? "st14-extractor-ui-eject" : "st14-extractor-ui-insert");
    }
}
